const $=s=>document.querySelector(s);
const state={code:sessionStorage.getItem('jarvisAccess')||'',busy:false,history:[]};
function bubble(who,text){const row=document.createElement('div');row.className='message '+(who==='SEN'?'user':'');const name=document.createElement('span');name.className='who';name.textContent=who;const body=document.createElement('div');body.className='bubble';body.textContent=text;row.append(name,body);$('#messages').append(row);$('#messages').scrollTop=$('#messages').scrollHeight}
async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+state.code},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json()}catch{throw Error('Sunucu yanıtı okunamadı.')}if(!r.ok)throw Error(data.error||'Bağlantı hatası.');return data}
async function status(){if(!state.code)return;try{const data=await api('status');$('#pc-status').textContent=({online:'Windows JARVIS bağlı',offline:'Windows JARVIS çevrimdışı',not_configured:'PC köprüsü ayarlanmadı'})[data.bridge]||'PC durumu bilinmiyor';$('#pc-dot').classList.toggle('online',data.bridge==='online')}catch(e){$('#pc-status').textContent=e.message;$('#pc-dot').classList.remove('online')}}
const labels={open_app:a=>`${a.name} uygulamasını aç`,search_web:a=>`Web’de ara: ${a.query}`,system_info:()=>`Sistem bilgilerini oku`,find_file:a=>`Dosya ara: ${a.name}`,add_note:a=>`Not kaydet: ${a.text}`,remind_me:a=>`${a.minutes} dakika sonra hatırlat: ${a.text}`};
function proposals(actions){$('#proposals').replaceChildren();for(const action of actions){if(!labels[action.name])continue;const card=document.createElement('div');card.className='proposal';const label=document.createElement('div');label.textContent='Windows işlemi: '+labels[action.name](action.args);const button=document.createElement('button');button.textContent='ONAYLA VE BİLGİSAYARA GÖNDER';button.onclick=async()=>{button.disabled=true;try{const job=await api('jobs','POST',{action});bubble('JARVIS','İşlem bilgisayara gönderildi. Yanıt bekleniyor...');await waitJob(job.id)}catch(e){bubble('JARVIS',e.message)}finally{card.remove()}};card.append(label,button);$('#proposals').append(card)}}
async function waitJob(id){for(let attempt=0;attempt<36;attempt++){await new Promise(r=>setTimeout(r,2000));try{const job=await api('jobs?id='+encodeURIComponent(id));if(job.status==='done'){bubble('JARVIS','Bilgisayar sonucu: '+job.result);return}}catch(e){bubble('JARVIS',e.message);return}}bubble('JARVIS','Bilgisayar yanıt vermedi. Windows uygulamasının açık olduğunu kontrol et.')}
async function send(text){text=text.trim();if(!text||state.busy)return;state.busy=true;$('#send').disabled=true;$('#orb').classList.add('busy');bubble('SEN',text);$('#proposals').replaceChildren();try{const data=await api('chat','POST',{message:text,history:state.history});bubble('JARVIS',data.text);state.history.push({role:'user',text},{role:'model',text:data.text});state.history=state.history.slice(-12);proposals(data.actions||[])}catch(e){bubble('JARVIS',e.message)}finally{state.busy=false;$('#send').disabled=false;$('#orb').classList.remove('busy')}}
$('#form').onsubmit=e=>{e.preventDefault();const field=$('#prompt');const value=field.value;if(state.busy)return;field.value='';send(value)};
document.querySelectorAll('[data-text]').forEach(button=>button.onclick=()=>send(button.dataset.text));
$('#gate-form').onsubmit=async e=>{e.preventDefault();state.code=$('#access').value.trim();try{await api('status');sessionStorage.setItem('jarvisAccess',state.code);$('#gate').hidden=true;$('#gate-error').textContent='';bubble('JARVIS','Merhaba! Buradan sohbet edebilir, Windows JARVIS bağlıysa izinli işlemleri onaylayarak gönderebilirsin.');status()}catch(e){state.code='';$('#gate-error').textContent=e.message}};
if(state.code){$('#gate').hidden=true;bubble('JARVIS','Merhaba! Nasıl yardımcı olabilirim?');status()}setInterval(status,18000);
const canvas=$('#particles'),ctx=canvas.getContext('2d');const points=Array.from({length:1000},(_,i)=>{const y=1-2*(i+.5)/1000,a=i*2.39996323,r=Math.sqrt(1-y*y);return{x:Math.cos(a)*r,y,z:Math.sin(a)*r}});let phase=0;
function frame(){phase+=$('#orb').classList.contains('busy')?.02:.006;ctx.clearRect(0,0,420,420);for(const p of points){const x=p.x*Math.cos(phase)-p.z*Math.sin(phase),z=p.x*Math.sin(phase)+p.z*Math.cos(phase),depth=3-z,px=210+x*280/depth,py=210+p.y*280/depth;ctx.fillStyle=z>0?`rgba(0,224,196,${.3+.6*(z+1)/2})`:`rgba(255,140,55,${.2+.45*(z+1)/2})`;ctx.beginPath();ctx.arc(px,py,z>0?1.1:.7,0,Math.PI*2);ctx.fill()}requestAnimationFrame(frame)}frame();
